export const isMainnet = process.env.NEXT_PUBLIC_NETWORK === 'mainnet';

export const NETWORK_CONFIG = {
  mainnet: {
    rpc: 'https://mainnet.sorobanrpc.com',
    horizon: 'https://horizon.stellar.org',
    passphrase: 'Public Global Stellar Network ; October 2015',
    explorerBase: 'https://stellar.expert/explorer/public',
    contracts: {
      corePool:           process.env.NEXT_PUBLIC_CORE_POOL_CONTRACT_ID || 'CDDA6FMHKC7Q6FY3D6HGTV273BKX7XJO5UHKFXDGN7VA6CDXGGFF7QPR',
      oracleAggregator:   process.env.NEXT_PUBLIC_ORACLE_AGGREGATOR_CONTRACT_ID || 'CAFJZQWSED6YAWZU3GWRTOCNPPCGBN32L7QV43XX5LZLFTK6JLN34DLN',
      backstop:           process.env.NEXT_PUBLIC_BACKSTOP_CONTRACT_ID || 'CBGN37EGC2VTOTROLR72BGCXEBZF2JGVHPPPN36IFKLVXBQLY3SXST6E',
      liquidationEngine:  process.env.NEXT_PUBLIC_LIQUIDATION_ENGINE_CONTRACT_ID || 'CCTXZNKEDNDA3ZGL6TQV2TSGNJ6HLUQCWXGIA6NOFKT53VESNDIYJRQH',
      governance:         process.env.NEXT_PUBLIC_GOVERNANCE_CONTRACT_ID || 'CBKGPWGKSKZF52CFHMTRR23TBWTPMRDIYZ4O2P5VS65BMHYH4DXMCJZC',
      compliance:         process.env.NEXT_PUBLIC_COMPLIANCE_CONTRACT_ID || 'CALI2BYU2JE6WVRUFYTS6MSBNEHGJ35P4AVCZYF3B6QOE3QKOB2PLE6M',
      ergoToken:          process.env.NEXT_PUBLIC_ERGO_TOKEN_CONTRACT_ID || 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWG',
    },
    assets: {
      XLM:  process.env.NEXT_PUBLIC_XLM_SAC || 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
      USDC: process.env.NEXT_PUBLIC_USDC_CONTRACT_ID || 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
      EURC: process.env.NEXT_PUBLIC_EURC_CONTRACT_ID || 'CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV',
      ERGO: process.env.NEXT_PUBLIC_ERGO_TOKEN_CONTRACT_ID || 'CDILV5HTHZGWQYRL6TJP3MUTSCRXXQSAUHBMASXPZVC2BS4I3QUE5IDQ',
    },
  },
  testnet: {
    rpc: 'https://soroban-testnet.stellar.org',
    horizon: 'https://horizon-testnet.stellar.org',
    passphrase: 'Test SDF Network ; September 2015',
    explorerBase: 'https://stellar.expert/explorer/testnet',
    contracts: {
      corePool:           process.env.NEXT_PUBLIC_TESTNET_CORE_POOL_CONTRACT_ID || 'CCTXZNKEDNDA3ZGL6TQV2TSGNJ6HLUQCWXGIA6NOFKT53VESNDIYJRQH',
      oracleAggregator:   process.env.NEXT_PUBLIC_TESTNET_ORACLE_AGGREGATOR_CONTRACT_ID || 'CBGN37EGC2VTOTROLR72BGCXEBZF2JGVHPPPN36IFKLVXBQLY3SXST6E',
      backstop:           process.env.NEXT_PUBLIC_TESTNET_BACKSTOP_CONTRACT_ID || 'CDDA6FMHKC7Q6FY3D6HGTV273BKX7XJO5UHKFXDGN7VA6CDXGGFF7QPR',
      liquidationEngine:  process.env.NEXT_PUBLIC_TESTNET_LIQUIDATION_ENGINE_CONTRACT_ID || 'CBKGPWGKSKZF52CFHMTRR23TBWTPMRDIYZ4O2P5VS65BMHYH4DXMCJZC',
      governance:         process.env.NEXT_PUBLIC_TESTNET_GOVERNANCE_CONTRACT_ID || 'CALI2BYU2JE6WVRUFYTS6MSBNEHGJ35P4AVCZYF3B6QOE3QKOB2PLE6M',
      compliance:         process.env.NEXT_PUBLIC_TESTNET_COMPLIANCE_CONTRACT_ID || 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWG',
      ergoToken:          process.env.NEXT_PUBLIC_TESTNET_ERGO_TOKEN_CONTRACT_ID || 'CDYJFYG7X4DPMAOQUUTYEK5KAOSTI7LEG4VDVSZ6KZQFM66LFHSLVBLZ',
    },
    assets: {
      XLM:  process.env.NEXT_PUBLIC_TESTNET_XLM_SAC || 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC',
      USDC: process.env.NEXT_PUBLIC_TESTNET_USDC_CONTRACT_ID || 'CB36S4EBJD34LVRY6KQHWTZPFN7HVURVTYOVTYIS2UZKSBPTCDMGYVSB',
      wBTC: process.env.NEXT_PUBLIC_TESTNET_WBTC_CONTRACT_ID || 'CDPU6K2FLBNLO4RIGQSRENFUEOLXHWXPY243WZBNOBUK5QEFBNXHSNSE',
      wETH: process.env.NEXT_PUBLIC_TESTNET_WETH_CONTRACT_ID || 'CC2DS3NYQJ5XSLWQWREIHJVIGW6KCVOB2E4IIKQ3KNXN647GLMJKDMJ5',
      ERGO: process.env.NEXT_PUBLIC_TESTNET_ERGO_TOKEN_CONTRACT_ID || 'CDYJFYG7X4DPMAOQUUTYEK5KAOSTI7LEG4VDVSZ6KZQFM66LFHSLVBLZ',
    },
  },
};

export let config = NETWORK_CONFIG[isMainnet ? 'mainnet' : 'testnet'];

export function setNetworkConfig(network: 'mainnet' | 'testnet') {
  config = NETWORK_CONFIG[network];
}
